import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overf`}
      >
        <Navbar/>
        {children}
        <div className="w-full h-full absolute right-0 top-0 overflow -z-10">
          <Image src='/ui-design/right-wave.svg' alt='right wave' width={1000} height={800} className="opacity-20 absolute -top-10 -right-10"/>
          <Image src='/ui-design/right-wave.svg' alt='right wave' width={1000} height={800} className="opacity-20 absolute -top-10 -right-10 rotate-6"/>
          <Image src='/ui-design/right-wave.svg' alt='right wave' width={1000} height={800} className="opacity-20 absolute top-[600px] -left-40 -rotate-12 scale-x-[-1]" />
        </div>
      </body>
    </html>
  );
}
